# Generated by Django 5.1.5 on 2025-02-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoproducto',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoProducto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
