# Generated by Django 5.1.5 on 2025-02-27 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_producto_carrito_carritoproducto_carrito_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
