# Generated by Django 5.1.5 on 2025-02-27 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_carrito_delete_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='iva',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='total_a_pagar',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/img'),
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.producto')),
            ],
        ),
        migrations.AlterField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(through='authentication.CarritoProducto', to='authentication.producto'),
        ),
    ]
